project_id = "pylfykpcqugkqsnssfsa"

[functions.paystack-initialize]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.grade-exam]
verify_jwt = true

[functions.subscription-payment]
verify_jwt = true

[functions.subscription-webhook]
verify_jwt = false
