project_id = "pylfykpcqugkqsnssfsa"

[functions.send-sms]
verify_jwt = true

[functions.send-email-notification]
verify_jwt = true

[functions.paystack-initialize]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.grade-exam]
verify_jwt = true

[functions.subscription-payment]
verify_jwt = true

[functions.subscription-webhook]
verify_jwt = false

[functions.registration-payment]
verify_jwt = false

[functions.validate-payment-gateway]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true

[functions.update-payment-secrets]
verify_jwt = false

[functions.delete-user]
verify_jwt = false